---
# .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false
contact_links:
  - name: ELK Admin Community Support
    url: https://github.com/JuanVilla424/elk-adm/discussions
    about: Please ask and answer questions here.
  - name: ELK Admin Security Reports
    url: https://juanvilla424.github.io/elk-adm/SECURITY
    about: Please report security vulnerabilities here.
